In [50]:
import random
import time
import numpy as np

a = []
for i in range(100000000):
    a.append(random.random()) 
    
t1 = time.time() # 当前时间
sum1=sum(a)
t2=time.time()


b=np.array(a) # numpy中的数组
t4=time.time()
sum3=np.sum(b)
t5=time.time()

print(t2-t1, t5-t4)


6.9656288623809814 0.6256351470947266


In [68]:
import numpy as np
list1 = [1,2,3,4]

oneArray = np.array(list1)
print(type(oneArray))
print(oneArray.shape) # (4,)


# [[1,2,3],[00,12,34]]
# [[1 2 3]
#  [4 5 6]]

<class 'numpy.ndarray'>
(4,)


In [52]:
t3 = np.arange(0,10,2)
print(t3)
print(type(t3))

[0 2 4 6 8]
<class 'numpy.ndarray'>


In [57]:
import numpy as np
list2 = [[1,2],[3,4],[5,6]]
twoArray = np.array(list2)
print(twoArray)

# print(twoArray.ndim)
# print(twoArray.shape) # (3, 2) (行，列)

# print(twoArray.size) # size = shape[0]*shape[1]


[[1 2]
 [3 4]
 [5 6]]
(3, 2)
6


In [71]:
four = np.array([[1,2,3],[4,5,6]]) 
array = np.array(four)
print(array)
print(array.shape)

# 修改原有数据
# array.shape=(3,2)
# print(array)

# 变换类型之后会返回一个新的数据
# arr = array.reshape(3,2)
# print(arr)
# print(array)

# arr = array.reshape((6,),order='F')
# print(arr)


[[1 2 3]
 [4 5 6]]
(2, 3)
[1 4 2 5 3 6]


In [72]:
import numpy as np

one = np.array([1,2,3,4])

list_one = one.tolist()

print(type(list_one))

<class 'list'>


In [73]:
f = np.array([1,2,3,4,5])
# 返回数组中每个元素的字节单位长度
# print(f.itemsize)
# 获取数据类型
print(f.dtype)

int64


In [75]:
# 数组和数做运算
t1 = np.arange(24).reshape((6,4))
print(t1)
print(t1+2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]]


In [77]:
t1 = np.arange(24).reshape((6,4))
t2 = np.arange(100,124).reshape((6,4))
print(t1)
print(t2)

print(t2-t1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[100 101 102 103]
 [104 105 106 107]
 [108 109 110 111]
 [112 113 114 115]
 [116 117 118 119]
 [120 121 122 123]]
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]]


In [79]:
t1 = np.arange(24).reshape((6,4))
t2 = np.arange(18).reshape((3,6))
print(t1)
print(t2)
# print(t1-t2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]


ValueError: operands could not be broadcast together with shapes (6,4) (3,6) 

In [82]:
t1 = np.arange(24).reshape((4,6))
t2 = np.arange(0,6)
print(t1)
print(t2)
print(t1-t2)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[0 1 2 3 4 5]
[[ 0  0  0  0  0  0]
 [ 6  6  6  6  6  6]
 [12 12 12 12 12 12]
 [18 18 18 18 18 18]]


In [84]:
t1 = np.arange(24).reshape((4,6))

print(t1)


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [88]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
print(a)
print(np.sum(a,axis=1))
print(np.sum(a,axis=0))

[[1 2 3]
 [4 5 6]]
[ 6 15]
[5 7 9]
